-- Invalidate cover letters generated by the legacy 2–3 sentence prompt.
-- Existing rows become v1; the application currently writes v2-rich.

ALTER TABLE cover_letters_cache
  ADD COLUMN IF NOT EXISTS prompt_version text NOT NULL DEFAULT 'v1';
